USE [DBUSER]
GO

/****** Object:  Table [dbo].[SYSTEM]    Script Date: 05/02/2022 21:48:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

EXEC P_REMOVE_FK N'DBO.SYSTEM'
GO

IF OBJECT_ID('DBO.SYSTEM', 'U') IS NOT NULL
	DROP TABLE DBO.[SYSTEM];

CREATE TABLE [DBO].[SYSTEM](
	[ID_SYSTEM] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_SYSTEM] [NVARCHAR](50) NOT NULL,
	[DS_DESCRIPTION] [NVARCHAR](500) NOT NULL,
	[BO_ACTIVE] [BIT] NOT NULL,
	[DT_CREATION] [DATETIME2](3) NOT NULL,
	[DT_ATUALIZATION] [DATETIME2](3) NOT NULL,
 CONSTRAINT [PK_SYSTEM] PRIMARY KEY CLUSTERED 
(
	[ID_SYSTEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [DBO].[SYSTEM] ADD  CONSTRAINT [C_SYSTEM_ACTIVE]  DEFAULT ((1)) FOR [BO_ACTIVE]
GO

ALTER TABLE [DBO].[SYSTEM] ADD  CONSTRAINT [C_SYSTEM_DT_CREATION]  DEFAULT (GETDATE()) FOR [DT_CREATION]
GO

ALTER TABLE [DBO].[SYSTEM] ADD  CONSTRAINT [C_SYSTEM_DT_ATUALIZATION]  DEFAULT (GETDATE()) FOR [DT_ATUALIZATION]
GO