USE [DBUSER]
GO

/****** Object:  Table [dbo].[USERKEYTYPE]    Script Date: 05/02/2022 21:48:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

EXEC P_REMOVE_FK N'DBO.USERKEYTYPE'
GO

IF OBJECT_ID('DBO.USERKEYTYPE', 'U') IS NOT NULL
	DROP TABLE DBO.[USERKEYTYPE];

CREATE TABLE [DBO].[USERKEYTYPE](
	[ID_USERKEYTYPE] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_KEYTYPE] [NVARCHAR](20) NOT NULL,  
 CONSTRAINT [PK_USERKEYTYPE] PRIMARY KEY CLUSTERED 
(
		[ID_USERKEYTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [DBO].[USERKEYTYPE] ADD CONSTRAINT [C_USERKEYTYPE_ID_USERKEYTYPE]  DEFAULT ((NEWID())) FOR [ID_USERKEYTYPE]
GO