USE [DBUSER]
GO

/****** Object:  Table [dbo].[USER]    Script Date: 05/02/2022 21:48:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

EXEC P_REMOVE_FK N'DBO.USER'
GO

IF OBJECT_ID('DBO.USER', 'U') IS NOT NULL
	DROP TABLE DBO.[USER];

CREATE TABLE [DBO].[USER](
	[ID_SYSTEM] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_LOGIN] [NVARCHAR](50) NOT NULL,
	[DS_EMAIL] [NVARCHAR](50) NOT NULL,
	[DS_USER] [NVARCHAR](50) NOT NULL,
	[DS_PHONE] [NVARCHAR](20) NULL,
	[BO_ACTIVE] [BIT] NOT NULL,
	[DT_CREATION] [DATETIME2](3) NOT NULL,
	[DT_ATUALIZATION] [DATETIME2](3) NOT NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID_SYSTEM], [DS_LOGIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [DBO].[USER] WITH CHECK ADD CONSTRAINT [FK_USERSYSTEM_SYSTEM] FOREIGN KEY([ID_SYSTEM]) REFERENCES [DBO].[SYSTEM]([ID_SYSTEM])
GO


ALTER TABLE [DBO].[USER] ADD  CONSTRAINT [C_USER_ACTIVE]  DEFAULT ((1)) FOR [BO_ACTIVE]
GO

ALTER TABLE [DBO].[USER] ADD  CONSTRAINT [C_USER_DT_CREATION]  DEFAULT (GETDATE()) FOR [DT_CREATION]
GO

ALTER TABLE [DBO].[USER] ADD  CONSTRAINT [C_USER_DT_ATUALIZATION]  DEFAULT (GETDATE()) FOR [DT_ATUALIZATION]
GO