USE [DBUSER]
GO

/****** Object:  Table [dbo].[USERKEYTYPEJOIN]    Script Date: 05/02/2022 21:48:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

EXEC P_REMOVE_FK N'DBO.USERKEYTYPEJOIN'
GO

IF OBJECT_ID('DBO.USERKEYTYPEJOIN', 'U') IS NOT NULL
	DROP TABLE DBO.[USERKEYTYPEJOIN];

CREATE TABLE [DBO].[USERKEYTYPEJOIN](
	[ID_SYSTEM] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_LOGIN] [NVARCHAR](50) NOT NULL,
	[ID_USERKEYTYPE] [UNIQUEIDENTIFIER] NOT NULL,
 CONSTRAINT [PK_USERKEYTYPEJOIN] PRIMARY KEY CLUSTERED 
(
		[ID_SYSTEM], [DS_LOGIN], [ID_USERKEYTYPE]  ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [DBO].[USERKEYTYPEJOIN] WITH CHECK ADD CONSTRAINT [FK_USERKEYTYPEJOIN_USERKEY] FOREIGN KEY([ID_SYSTEM], [DS_LOGIN]) REFERENCES [DBO].[USERKEY]([ID_SYSTEM], [DS_LOGIN])
GO

ALTER TABLE [DBO].[USERKEYTYPEJOIN] CHECK CONSTRAINT [FK_USERKEYTYPEJOIN_USERKEY]
GO

ALTER TABLE [DBO].[USERKEYTYPEJOIN] WITH CHECK ADD CONSTRAINT [FK_USERKEYTYPEJOIN_USERKEYTYPE] FOREIGN KEY([ID_USERKEYTYPE]) REFERENCES [DBO].[USERKEYTYPE]([ID_USERKEYTYPE])
GO

ALTER TABLE [DBO].[USERKEYTYPEJOIN] CHECK CONSTRAINT [FK_USERKEYTYPEJOIN_USERKEYTYPE]
GO