USE [DBUSER]
GO

/****** Object:  Table [dbo].[USERKEY]    Script Date: 05/02/2022 21:48:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

EXEC P_REMOVE_FK N'USERKEY'
GO

IF OBJECT_ID('DBO.USERKEY', 'U') IS NOT NULL
	DROP TABLE DBO.[USERKEY];

CREATE TABLE [DBO].[USERKEY](
	[ID_SYSTEM] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_LOGIN] [NVARCHAR](50) NOT NULL,
	[DS_KEY] [NVARCHAR](MAX) NOT NULL,
	[DT_CREATION] [DATETIME2](3) NOT NULL,
	[DT_ATUALIZATION] [DATETIME2](3) NOT NULL,
 CONSTRAINT [PK_USERKEY] PRIMARY KEY CLUSTERED 
(
		[ID_SYSTEM], [DS_LOGIN]  ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [DBO].[USERKEY] WITH CHECK ADD CONSTRAINT [FK_USERKEY_USER] FOREIGN KEY([ID_SYSTEM], [DS_LOGIN]) REFERENCES [DBO].[USER]([ID_SYSTEM], [DS_LOGIN])
GO

ALTER TABLE [DBO].[USERKEY] CHECK CONSTRAINT [FK_USERKEY_USER]
GO

ALTER TABLE [DBO].[USERKEY] ADD CONSTRAINT [C_USERKEY_DT_CREATION]  DEFAULT (GETDATE()) FOR [DT_CREATION]
GO

ALTER TABLE [DBO].[USERKEY] ADD CONSTRAINT [C_USERKEY_DT_ATUALIZATION]  DEFAULT (GETDATE()) FOR [DT_ATUALIZATION]
GO

ALTER TABLE [DBO].[USERKEY] ADD CONSTRAINT [C_USERKEY_DS_KEY] CHECK (ISJSON(DS_KEY)=1)
GO

