USE [DBUSER]
GO

/****** Object:  Table [dbo].[USERSESSION]    Script Date: 05/02/2022 21:48:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

EXEC P_REMOVE_FK N'DBO.USERSESSION'
GO

IF OBJECT_ID('DBO.USERSESSION', 'U') IS NOT NULL
	DROP TABLE DBO.[USERSESSION];

CREATE TABLE [DBO].[USERSESSION](
	[ID_SYSTEM] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_LOGIN] [NVARCHAR](50) NOT NULL,
	[DS_SESSION] [NVARCHAR] (MAX) NOT NULL,
	[DT_SESSION] [

 CONSTRAINT [PK_USERSESSION] PRIMARY KEY CLUSTERED 
(
	[ID_SYSTEM], [DS_LOGIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [DBO].[USERSESSION] ADD  CONSTRAINT [C_USERSESSION_ACTIVE]  DEFAULT ((1)) FOR [BO_ACTIVE]
GO

ALTER TABLE [DBO].[USERSESSION] ADD  CONSTRAINT [C_USERSESSION_DT_CREATION]  DEFAULT (GETDATE()) FOR [DT_CREATION]
GO

ALTER TABLE [DBO].[USERSESSION] ADD  CONSTRAINT [C_USERSESSION_DT_ATUALIZATION]  DEFAULT (GETDATE()) FOR [DT_ATUALIZATION]
GO